spring:
  profiles:
    include: common-dev
  application:
    name: service-data-dts
  #数据源
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ${common.mysql.dts.driver-class-name}
      url: ${common.mysql.dts.url}
      username: ${common.mysql.dts.username}
      password: ${common.mysql.dts.password}
  jpa:
    hibernate:
      ddl-auto: update

  # email
  mail:
    host: smtp.qq.com
    port: 25
    username: test@qq.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory


management:
  health:
    mail:
      enabled: false
  server:
    servlet:
      context-path: /actuator

mybatis-plus:
  # mapper.xml文件扫描
  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
      # 数据库类型
      db-type: mysql
    banner: false
  # mybatis原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    type-handlers-package: com.platform.admin.core.handler

#flinkx-job, access token
dts:
  job:
    accessToken:
    #i18n (default empty as chinese, "en" as english)
    i18n:
    ## triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
      ### log retention days
    logretentiondays: 30
  executor:
    chunjunHome: E:/chunjun/chunjun.py
    chunjunjsonPath: E:/chunjun/job/
    chunjunlogHome: E:/chunjun/job-log
    dataxHome: E:/datax/datax.py
    dataxjsonPath: E:/datax/job/
    dataxlogHome: E:/datax/job-log
datasource:
  aes:
    key: AD42F6697B035B75


# 注册中心配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
    ip-address: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8610/eureka
